# -*- coding: utf-8 -*-
"""Exwarrdo_AI_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MySVLSWSVc1IhBPRnppl-mHvuWVoE-2
"""

import streamlit as st
from PIL import Image
import numpy as np

# ------------------ CONFIG ------------------
st.set_page_config(
    page_title="Exwarrdo | Asset Wellness Platform",
    layout="centered"
)

# ------------------ HEADER ------------------
st.title("🪑 Exwarrdo")
st.subheader("AI-powered Furniture Asset Wellness Platform")

st.markdown(
    """
    Exwarrdo transforms furniture from a **disposable expense** into a **managed, health-tracked asset**
    through AI diagnostics and lifecycle services.
    """
)

# ------------------ TABS ------------------
tab1, tab2 = st.tabs(["🧠 Product", "🛠️ Service"])

# ------------------ PRODUCT TAB ------------------
with tab1:
    st.header("Product: Digital Furniture HealthCard")

    st.markdown("""
    **Core Capabilities**
    - QR-linked Digital HealthCard per furniture item
    - AI-based photo diagnostics
    - Real-time asset health score
    - Lifecycle & service history tracking
    - Cloud-based, scalable dashboard
    """)

    st.divider()

    st.subheader("📋 Register Furniture Asset")

    asset_name = st.text_input("Furniture Name", "Queen Size Bed")
    material = st.selectbox("Primary Material", ["Wood", "Engineered Wood", "Metal", "Mixed"])
    age = st.slider("Age of Furniture (Years)", 0, 10, 2)

    uploaded_image = st.file_uploader("Upload latest furniture photo", type=["jpg", "png", "jpeg"])

    if uploaded_image:
        image = Image.open(uploaded_image)
        st.image(image, caption="Uploaded Asset Image", use_column_width=True)

        # ---- Simulated AI Health Score ----
        health_score = max(30, 100 - (age * 8) - np.random.randint(5, 20))

        st.success(f"🩺 Asset Health Score: **{health_score}/100**")

        if health_score > 75:
            st.info("Status: Healthy – No action required")
        elif health_score > 50:
            st.warning("Status: Monitor – Preventive maintenance recommended")
        else:
            st.error("Status: Attention Required – Repair or redesign suggested")

    st.caption("⚠️ AI diagnostics shown here are simulated for pilot demonstration.")

# ------------------ SERVICE TAB ------------------
with tab2:
    st.header("Service: Managed Furniture Lifecycle")

    st.markdown("""
    **Exwarrdo Services**
    - Subscription-based extended warranty (post manufacturer warranty)
    - Predictive maintenance coordination
    - Repair, refurbishment, and redesign support
    - Asset swap, buy-back, or responsible replacement
    - Vetted local service partners (pay-per-task model)
    """)

    st.divider()

    st.subheader("🔄 Decision Workflow")

    decision = st.radio(
        "Based on health diagnostics, recommended action:",
        ["Repair", "Redesign", "Replace / Swap"]
    )

    if decision == "Repair":
        st.success("✔ Repair request raised with nearest verified service partner")
        st.caption("Expected turnaround: 3–5 working days")

    elif decision == "Redesign":
        st.info("🎨 Redesign option selected (polish / upholstery / finish update)")
        st.caption("Ideal for aesthetic refresh without replacement")

    else:
        st.warning("♻ Asset eligible for swap / buy-back")
        st.caption("Prevents landfill waste and reduces replacement cost")

    st.divider()

    st.subheader("💳 Subscription Model (Example)")

    st.markdown("""
    - ₹6,000 — 3 months / 3 assets
    - ₹12,000 — 6 months / 6 assets
    - ₹24,000 — 12 months / 12 assets
    """)

# ------------------ FOOTER ------------------
st.divider()
st.caption("Exwarrdo | PropTech × Circular Economy | Pilot MVP")
